### ISSUE TITLE
Missing parameter ResultsPath

### ISSUE THREAD

**Issue by HauHe** [OSeMOSYS/otoole#103]
After adding a csv called `ResultsPath`to a datapackage and converting the datapackage to a datafile, the paramter `ResultsPath` is not inlcuded in the datafile.

**Comment by HauHe** [comment]
Hi @willu47,

I have tried to add the `param ResultPath` to otoole. I edited the files `datapackage.json`and `config.yaml` in `src>otoole>preprocesses`. However, either my additions are not right or I'm missing something else. When testing it I get the error below. Do you have any suggestion what I need to change?
You can find the modified version here: [HauHe/otoole](https://github.com/HauHe/otoole)

`(HauHe_otoole) OSeMOSYS_step/data - (main) > otoole -vvv convert datafile datapackage simplicity.txt simplicity
Traceback (most recent call last):
  File "/opt/anaconda3/envs/HauHe_otoole/bin/otoole", line 33, in <module>
    sys.exit(load_entry_point('otoole', 'console_scripts', 'otoole')())
  File "/Users/cotti/GitHub/HauHe/otoole/src/otoole/cli.py", line 287, in main
    args.func(args)
  File "/Users/cotti/GitHub/HauHe/otoole/src/otoole/cli.py", line 145, in conversion_matrix
    read_strategy = ReadDatafile()
  File "/Users/cotti/GitHub/HauHe/otoole/src/otoole/input.py", line 152, in __init__
    self._input_config = self._add_dtypes(self._input_config)
  File "/Users/cotti/GitHub/HauHe/otoole/src/otoole/input.py", line 158, in _add_dtypes
    for column in details["indices"] + ["VALUE"]:
KeyError: 'indices'`
