### ISSUE TITLE
Error appearing when trying to setup OSeMOSYS via otoole

### ISSUE THREAD

**Issue by AgnesBelt** [OSeMOSYS/otoole#6]
After having installed otoole on my computer, I tried to setup the OSeMOSYS environment, but I got the following error:
```
Traceback (most recent call last):
  File "c:\nobackup\beltramo\anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\nobackup\beltramo\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Nobackup\beltramo\Anaconda\Scripts\otoole.exe\__main__.py", line 9, in <module>
  File "c:\nobackup\beltramo\anaconda\lib\site-packages\otoole\cli.py", line 92, in main
    logging.basicConfig(filename='myapp.log', level=logging.DEBUG, filemode='w')
  File "c:\nobackup\beltramo\anaconda\lib\logging\__init__.py", line 1900, in basicConfig
    h = FileHandler(filename, mode)
  File "c:\nobackup\beltramo\anaconda\lib\logging\__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "c:\nobackup\beltramo\anaconda\lib\logging\__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: 'C:\\myapp.log'
```

**Comment by willu47** [comment]
Fixed by removing logging file creation in #4
