### ISSUE TITLE
Simplicity example -- errors with datapackage.json

### ISSUE THREAD

**Issue by wogandavid** [OSeMOSYS/otoole#64]
I receive an error message when following the Getting Started commands on the [otoole documentation page](https://otoole.readthedocs.io/en/stable/index.html). I created and activating the environment, installed otoole via pip (0.8.2) and tried to run the following command:

`otoole convert datapackage datafile https://zenodo.org/record/3479823/files/KTH-dESA/simplicity-v0.1a0.zip simplicity.txt`

When doing so, I am presented with the following error message:

```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/opt/miniconda3/envs/otoole-env/lib/python3.7/site-packages/otoole/cli.py", line 294, in exception_handler
    print("{}: {}".format(exception_type.__name__, exception.message))
AttributeError: 'HTTPError' object has no attribute 'message'

Original exception was:
Traceback (most recent call last):
  File "/opt/miniconda3/envs/otoole-env/bin/otoole", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/otoole-env/lib/python3.7/site-packages/otoole/cli.py", line 299, in main
    args.func(args)
  File "/opt/miniconda3/envs/otoole-env/lib/python3.7/site-packages/otoole/cli.py", line 150, in conversion_matrix
    context.convert(args.from_path, args.to_path)
  File "/opt/miniconda3/envs/otoole-env/lib/python3.7/site-packages/otoole/input.py", line 134, in convert
    inputs, default_values = self._read(input_filepath)
  File "/opt/miniconda3/envs/otoole-env/lib/python3.7/site-packages/otoole/input.py", line 118, in _read
    return self._read_strategy.read(filepath)
  File "/opt/miniconda3/envs/otoole-env/lib/python3.7/site-packages/otoole/read_strategies.py", line 188, in read
    inputs = read_datapackage(filepath)
  File "/opt/miniconda3/envs/otoole-env/lib/python3.7/site-packages/pandas_datapackage_reader/__init__.py", line 65, in read_datapackage
    r.raise_for_status()
  File "/opt/miniconda3/envs/otoole-env/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: https://zenodo.org/record/3479823/files/KTH-dESA/simplicity-v0.1a0.zip/datapackage.json
```
I am able to manually download the zip file from Zenodo. When running the command using the zip file as the input file, the following error appears:

```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/opt/miniconda3/envs/otoole-env/lib/python3.7/site-packages/otoole/cli.py", line 294, in exception_handler
    print("{}: {}".format(exception_type.__name__, exception.message))
AttributeError: 'FileNotFoundError' object has no attribute 'message'

Original exception was:
Traceback (most recent call last):
  File "/opt/miniconda3/envs/otoole-env/bin/otoole", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/otoole-env/lib/python3.7/site-packages/otoole/cli.py", line 299, in main
    args.func(args)
  File "/opt/miniconda3/envs/otoole-env/lib/python3.7/site-packages/otoole/cli.py", line 150, in conversion_matrix
    context.convert(args.from_path, args.to_path)
  File "/opt/miniconda3/envs/otoole-env/lib/python3.7/site-packages/otoole/input.py", line 134, in convert
    inputs, default_values = self._read(input_filepath)
  File "/opt/miniconda3/envs/otoole-env/lib/python3.7/site-packages/otoole/input.py", line 118, in _read
    return self._read_strategy.read(filepath)
  File "/opt/miniconda3/envs/otoole-env/lib/python3.7/site-packages/otoole/read_strategies.py", line 188, in read
    inputs = read_datapackage(filepath)
  File "/opt/miniconda3/envs/otoole-env/lib/python3.7/site-packages/pandas_datapackage_reader/__init__.py", line 67, in read_datapackage
    with open(url_or_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'KTH-dESA/simplicity-v0.1a0.zip/datapackage.json'
```

The next step was to unpack the zip and run the command pointing at the directory:

`otoole convert datapackage datafile KTH-dESA-simplicity-1c9d5bb simplicity.txt`

```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/opt/miniconda3/envs/otoole-env/lib/python3.7/site-packages/otoole/cli.py", line 294, in exception_handler
    print("{}: {}".format(exception_type.__name__, exception.message))
AttributeError: 'KeyError' object has no attribute 'message'

Original exception was:
Traceback (most recent call last):
  File "/opt/miniconda3/envs/otoole-env/bin/otoole", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/otoole-env/lib/python3.7/site-packages/otoole/cli.py", line 299, in main
    args.func(args)
  File "/opt/miniconda3/envs/otoole-env/lib/python3.7/site-packages/otoole/cli.py", line 150, in conversion_matrix
    context.convert(args.from_path, args.to_path)
  File "/opt/miniconda3/envs/otoole-env/lib/python3.7/site-packages/otoole/input.py", line 134, in convert
    inputs, default_values = self._read(input_filepath)
  File "/opt/miniconda3/envs/otoole-env/lib/python3.7/site-packages/otoole/input.py", line 118, in _read
    return self._read_strategy.read(filepath)
  File "/opt/miniconda3/envs/otoole-env/lib/python3.7/site-packages/otoole/read_strategies.py", line 189, in read
    default_resource = inputs.pop("default_values").set_index("name").to_dict()
KeyError: 'default_values'
```
I am not sure if the example code is supposed to curl the zip file and extract, etc. In any case, when downloading and unpacking the zip, the datapackage.json file is not able to be read. Perhaps I am not following the instructions properly?

I am developing on macOS 10.15.6 using the dependencies listed in the environment instructions.

**Comment by willu47** [comment]
Ooof, thanks for this.  I'll amend the getting started guide as this is a bit out of date, and I also need to update the simplicity example. Thanks for the reminder!
