### ISSUE TITLE
`otoole --version` results in error

### ISSUE THREAD

**Issue by willu47** [OSeMOSYS/otoole#69]
```python
$ otoole --version
Traceback (most recent call last):
  File "/Users/wusher/miniconda3/envs/snakemake/bin/otoole", line 5, in <module>
    from otoole.cli import main
  File "/Users/wusher/miniconda3/envs/snakemake/lib/python3.6/site-packages/otoole/cli.py", line 47, in <module>
    from otoole.input import Context
  File "/Users/wusher/miniconda3/envs/snakemake/lib/python3.6/site-packages/otoole/input.py", line 32
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
(snakemake) wusher-mbp:gui_workflow wusher$ otoole -v
Traceback (most recent call last):
  File "/Users/wusher/miniconda3/envs/snakemake/bin/otoole", line 5, in <module>
    from otoole.cli import main
  File "/Users/wusher/miniconda3/envs/snakemake/lib/python3.6/site-packages/otoole/cli.py", line 47, in <module>
    from otoole.input import Context
  File "/Users/wusher/miniconda3/envs/snakemake/lib/python3.6/site-packages/otoole/input.py", line 32
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

**Comment by willu47** [comment]
`from __future__ import annotations` was introduced in Python 3.7. Suggest adding a >=3.7 qualifier to the setup.cfg?
