### ISSUE TITLE
otoole convert cbc result to csv

### ISSUE THREAD

**Issue by wogandavid** [OSeMOSYS/otoole#77]
This may be related to #21 .I am trying to convert a cbc solution file to a folder of csv files using the otoole from the command line. I generate the lp file using glpsol from the osemosys-fast code:

`glpsol -d data/datafile_from_python.txt -m model/osemosys-fast.txt -o  --wlp results/jpn.lp --check`

then solve with cbc:

`cbc results/jpn.lp solve solu results/results.sol`

then call otoole for the conversion:

`otoole results cbc csv results/results.sol ./results --input_datafile data/datafile_from_python.txt`

The model solves successfully. The error reported during conversion is: 

```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/otoole/cli.py", line 294, in exception_handler
    print("{}: {}".format(exception_type.__name__, exception.message))
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/pyparsing.py", line 336, in __getattr__
    raise AttributeError(aname)
AttributeError: message

Original exception was:
Traceback (most recent call last):
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/bin/otoole", line 8, in <module>
    sys.exit(main())
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/otoole/cli.py", line 299, in main
    args.func(args)
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/otoole/cli.py", line 99, in result_matrix
    args.from_path, args.to_path, args.input_datafile, "datafile"
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/otoole/results/convert.py", line 323, in convert_cbc_to_csv
    input_data, _ = ReadDatafile().read(input_data_path)
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/otoole/read_strategies.py", line 200, in read
    amply_datafile = self.read_in_datafile(filepath, config)
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/otoole/read_strategies.py", line 218, in read_in_datafile
    datafile_parser.load_file(datafile)
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/amply/amply.py", line 754, in load_file
[osemosys-fast.txt](https://github.com/OSeMOSYS/otoole/files/5310220/osemosys-fast.txt)

    self.load_string(f.read())
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/amply/amply.py", line 745, in load_string
    for obj in grammar.parseString(string):
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/pyparsing.py", line 1955, in parseString
    raise exc
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/pyparsing.py", line 3814, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected end of text, found 'p'  (at char 171), (line:8, col:1)
```

I am not sure if this is related to otoole or with my specific model; however it does solve using both GLPK and CBC. I am not entirely sure where the parsing error is occuring, possibly in the input data file? The input data file and osemosys fast code are attached.

I am using otoole 0.8.4.
[datafile_from_python.txt](https://github.com/OSeMOSYS/otoole/files/5310271/datafile_from_python.txt)
[osemosys-fast.txt](https://github.com/OSeMOSYS/otoole/files/5310272/osemosys-fast.txt)

**Comment by willu47** [comment]
An interesting bug @wogandavid - thanks for sharing the input file.  Obviously, the model runs fine in the fast code, but I've tracked down the error to an incompatibility with the otoole dependency Amply and your naming convention. Amply implements parsing of AMPL or GMPL datafiles using the pyparsing library. Amply expects all set elements to start with alpha characters, and does not allow the use of underscores or any other whitespace characters. I'm the maintainer for Amply, so I'll log an issue over there and work on a fix - I think it is reasonable to allow underscores and numerical values as set elements.

**Comment by wogandavid** [comment]
thanks, @willu47 , that makes sense.

**Comment by willu47** [comment]
Hi @wogandavid - if you now update to `v0.1.3` of amply, you should be able to convert your file successfully.

**Comment by willu47** [comment]
> Hi @wogandavid - if you now update to `v0.1.3` of amply, you should be able to convert your file successfully.

Looks like the deployment to PyPi failed... will try to sort this soon

**Comment by wogandavid** [comment]
@willu47 I was able to pull down amply `v0.1.4` and get my example working. Thanks! I extended my testing and have encountered an additional issue. I follow the same procedure as noted in the original post. CBC successfully finds a solution. When I try to convert the cbc solution file to csv, I receive the following message:

```
/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/pandas/core/frame.py:3065: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
Error in sys.excepthook:
Traceback (most recent call last):
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/otoole/cli.py", line 294, in exception_handler
    print("{}: {}".format(exception_type.__name__, exception.message))
AttributeError: 'TypeError' object has no attribute 'message'

Original exception was:
Traceback (most recent call last):
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 142, in na_arithmetic_op
    result = expressions.evaluate(op, left, right)
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/pandas/core/computation/expressions.py", line 230, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/pandas/core/computation/expressions.py", line 68, in _evaluate_standard
    return op(a, b)
TypeError: can't multiply sequence by non-int of type 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/bin/otoole", line 8, in <module>
    sys.exit(main())
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/otoole/cli.py", line 299, in main
    args.func(args)
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/otoole/cli.py", line 99, in result_matrix
    args.from_path, args.to_path, args.input_datafile, "datafile"
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/otoole/results/convert.py", line 327, in convert_cbc_to_csv
    csv = convert_cbc_to_df(from_file, input_data)
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/otoole/results/convert.py", line 296, in convert_cbc_to_df
    csv = convert_dataframe_to_csv(df, input_data)
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/otoole/results/convert.py", line 235, in convert_dataframe_to_csv
    df = results_package[name]
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/otoole/results/result_package.py", line 98, in __getitem__
    results = self.result_mapper[name]()
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/otoole/results/result_package.py", line 194, in annual_emissions
    data = mid.mul(rate_of_activity, fill_value=0.0)
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 651, in f
    new_data = self._combine_frame(other, na_op, fill_value)
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/pandas/core/frame.py", line 5865, in _combine_frame
    new_data = ops.dispatch_to_series(self, other, _arith_op)
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 275, in dispatch_to_series
    bm = left._mgr.operate_blockwise(right._mgr, array_op)
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 364, in operate_blockwise
    return operate_blockwise(self, other, array_op)
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/pandas/core/internals/ops.py", line 38, in operate_blockwise
    res_values = array_op(lvals, rvals)
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/pandas/core/frame.py", line 5863, in _arith_op
    return func(left, right)
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 189, in arithmetic_op
    res_values = na_arithmetic_op(lvalues, rvalues, op)
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 149, in na_arithmetic_op
    result = masked_arith_op(left, right, op)
  File "/mnt/c/Users/david/GitHub/otoole2/.snakemake/conda/9815011e/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 91, in masked_arith_op
    result[mask] = op(xrav[mask], yrav[mask])
TypeError: can't multiply sequence by non-int of type 'float'
```
Any thoughts? The model data file and code are attached.

otoole = 0.8.4
amply = 0.1.4

[datafile_float.txt](https://github.com/OSeMOSYS/otoole/files/5327323/datafile_float.txt)
[osemosys-fast.txt](https://github.com/OSeMOSYS/otoole/files/5327329/osemosys-fast.txt)

**Comment by willu47** [comment]
Hi @wogandavid - I believe this might have something to do with the pandas version you are using.  Please could you update pandas and try again?

**Comment by wogandavid** [comment]
@willu47 I did some more testing. No issues with otoole. I disccovered in the cbc solution file that the level of some decision variables were negative and beyond the tolerance of the solution algorithm (e.g., -1e-8). I think the negative values were then interpreted as something not a float value, which caused an issue in the pandas transformations. I reran the model to eliminate that result and everything works as expected.

**Comment by willu47** [comment]
I've investigated further into the final issue identified by @wogandavid:

> I discovered in the cbc solution file that the level of some decision variables were negative and beyond the tolerance of the solution algorithm (e.g., -1e-8).

CBC doesn't announce clearly when some of the decision variables are outside their bounds. For example, both the main decision variables `RateOfActivity` and `NewCapacity` have lower bounds of 0.  Negative values indicate some degree of infeasibility in the solution and that there is a problem with the solution.  I will open a new issue to warn otoole users of this, and either raise an error, or somehow deal with the data issues.
